apiVersion: v1
kind: Service
metadata:
  name: nodejs-demo
  labels:
    app.kubernetes.io/name: nodejs-demo
    app.kubernetes.io/version: "18"
    app.kubernetes.io/component: webapp
    app.kubernetes.io/part-of: argocd-gitops-lab
spec:
  selector:
    app.kubernetes.io/name: nodejs-demo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
  type: ClusterIP