apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
data:
  alert_rules.yml: |
    groups:
    - name: example
      rules:
      - alert: HighRequestLatency
        expr: http_request_duration_seconds{quantile="0.5"} > 0.5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: High request latency