apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
  namespace: default
data:
  vault-agent-config.hcl: |
    exit_after_auth = false
    pid_file = "/home/vault/pidfile"

    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "nodejs-role"
        }
      }

      sink "file" {
        config = {
          path = "/home/vault/.vault-token"
        }
      }
    }

    template {
      destination = "/vault/secrets/db-creds"
      contents = |
        {{ with secret "database/creds/nodejs-role" }}
        db_username="{{ .Data.username }}"
        db_password="{{ .Data.password }}"
        {{ end }}
      command = "chmod 644 /vault/secrets/db-creds"
    }