apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodejs-app-sa
  namespace: argocd-gitops-dev
  labels:
    app.kubernetes.io/name: nodejs-app
    app.kubernetes.io/part-of: argocd-gitops-lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
  namespace: argocd-gitops-dev
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: argocd-gitops-lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sa
  namespace: argocd-gitops-dev
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: argocd-gitops-lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodejs-app-sa
  namespace: argocd-gitops-prod
  labels:
    app.kubernetes.io/name: nodejs-app
    app.kubernetes.io/part-of: argocd-gitops-lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
  namespace: argocd-gitops-prod
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: argocd-gitops-lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sa
  namespace: argocd-gitops-prod
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: argocd-gitops-lab
